2024-02-20 12:13:54,677 - ERROR: Error Controladora Device 10.117.115.111
2024-02-20 12:13:54,677 - ERROR: Error Controladora Device 10.117.115.111
2024-02-20 12:13:54,678 - ERROR: Traceback (most recent call last):
  File "/home/donkami/Sona/devnet-candelaria/Services/Mesh/controladora.py", line 35, in get_data_controladora
    data_pala = net_connect.send_command(f"sh wireless client summary detail ipv4 | inc {device_ip}") #! Ip Pala
  File "/home/donkami/.local/lib/python3.10/site-packages/netmiko/utilities.py", line 592, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/donkami/.local/lib/python3.10/site-packages/netmiko/base_connection.py", line 1721, in send_command
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 
Pattern not detected: 'WLC\\-9800\\-MESH\\-CD>' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.



2024-02-20 12:13:54,678 - ERROR: Traceback (most recent call last):
  File "/home/donkami/Sona/devnet-candelaria/Services/Mesh/controladora.py", line 35, in get_data_controladora
    data_pala = net_connect.send_command(f"sh wireless client summary detail ipv4 | inc {device_ip}") #! Ip Pala
  File "/home/donkami/.local/lib/python3.10/site-packages/netmiko/utilities.py", line 592, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/donkami/.local/lib/python3.10/site-packages/netmiko/base_connection.py", line 1721, in send_command
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 
Pattern not detected: 'WLC\\-9800\\-MESH\\-CD>' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.



2024-02-20 12:16:02,765 - ERROR: Error Controladora Device 10.117.115.121
2024-02-20 12:16:02,765 - ERROR: Error Controladora Device 10.117.115.121
2024-02-20 12:16:02,766 - ERROR: Traceback (most recent call last):
  File "/home/donkami/Sona/devnet-candelaria/Services/Mesh/controladora.py", line 35, in get_data_controladora
    data_pala = net_connect.send_command(f"sh wireless client summary detail ipv4 | inc {device_ip}") #! Ip Pala
  File "/home/donkami/.local/lib/python3.10/site-packages/netmiko/utilities.py", line 592, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/donkami/.local/lib/python3.10/site-packages/netmiko/base_connection.py", line 1721, in send_command
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 
Pattern not detected: 'WLC\\-9800\\-MESH\\-CD>' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.



2024-02-20 12:16:02,766 - ERROR: Traceback (most recent call last):
  File "/home/donkami/Sona/devnet-candelaria/Services/Mesh/controladora.py", line 35, in get_data_controladora
    data_pala = net_connect.send_command(f"sh wireless client summary detail ipv4 | inc {device_ip}") #! Ip Pala
  File "/home/donkami/.local/lib/python3.10/site-packages/netmiko/utilities.py", line 592, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/donkami/.local/lib/python3.10/site-packages/netmiko/base_connection.py", line 1721, in send_command
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 
Pattern not detected: 'WLC\\-9800\\-MESH\\-CD>' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.



2024-02-20 12:18:15,482 - ERROR: Error Controladora Device 10.117.115.183
2024-02-20 12:18:15,482 - ERROR: Error Controladora Device 10.117.115.183
2024-02-20 12:18:15,483 - ERROR: Traceback (most recent call last):
  File "/home/donkami/Sona/devnet-candelaria/Services/Mesh/controladora.py", line 38, in get_data_controladora
    output = net_connect.send_command("sh wireless client mac-address " + data_pala.split()[0] + " detail")
IndexError: list index out of range

2024-02-20 12:18:15,483 - ERROR: Traceback (most recent call last):
  File "/home/donkami/Sona/devnet-candelaria/Services/Mesh/controladora.py", line 38, in get_data_controladora
    output = net_connect.send_command("sh wireless client mac-address " + data_pala.split()[0] + " detail")
IndexError: list index out of range

